apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      containers:
        - name: mono
          image: gcr.io/eleanor-270008/mono:v1
          env:
            - name: "BUCKET_NAME"
              value: mono
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/serviceaccount.json"
        - name: machine
          image: gcr.io/eleanor-270008/machine:v1
          env:
            - name: "BUCKET_NAME"
              value: machine
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/serviceaccount.json"
          volumeMounts:
            - name: "serviceaccount"
              mountPath: "/var/run/secret/cloud.google.com"
            - name: "certs"
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: "serviceaccount"
          secret:
            secretName: "my-app-sa-key"
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"