name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  generate:
    name: Generate
    runs-on: ubuntu-latest
    container: grpc/go

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: set-go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: protoc-gen-micro
      run: |
        GO111MODULE=on go get -u github.com/micro/protoc-gen-micro/v2

    - name: Set path
      run: |
        export PATH=$PATH:$GOPATH/bin/

    - name: Generate code
      run: |
        protoc --proto_path=$GOPATH:. --micro_out=. --go_out=. proto/Devbench.proto


  build-mono:
    name: Build-Mono
    runs-on: ubuntu-latest
    container: golang:latest
    needs: generate
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd Mono
        go fmt $(go list ./... | grep -v /vendor/)
        go vet $(go list ./... | grep -v /vendor/)
        go test -race $(go list ./... | grep -v /vendor/)
        go build -race -ldflags "-extldflags '-static'" -o mybinary

  build-machine:
    name: Build-Machine
    runs-on: ubuntu-latest
    container: golang:latest
    needs: generate
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd Machine
        go fmt $(go list ./... | grep -v /vendor/)
        go vet $(go list ./... | grep -v /vendor/)
        go test -race $(go list ./... | grep -v /vendor/)
        go build -race -ldflags "-extldflags '-static'" -o mybinary
